/**
 * Giscus (GitHub Discussions) configuration — the single place to edit when the
 * comment backend changes. See docs/engagement-setup.md for the full walkthrough.
 *
 * The defaults below are the real values giscus.app generated for this
 * repository. Re-verified 2026-10-09 through the GitHub REST API: the repo is
 * public, has_discussions is true, and its node_id is R_kgDOVAl-3A. These are
 * public identifiers, never secrets.
 *
 * Two deliberate choices:
 *   - mapping stays 'pathname' with strict '1'. Every article therefore keeps its
 *     own discussion; fuzzy title matching could otherwise merge two threads.
 *   - the theme is computed from the site's own light/dark toggle rather than
 *     'preferred_color_scheme', because this site has an explicit switch that
 *     does not follow the operating system setting.
 *
 * Every value can also be overridden through the public environment variables
 * declared in src/env.ts:
 *   PUBLIC_GISCUS_REPO, PUBLIC_GISCUS_REPO_ID,
 *   PUBLIC_GISCUS_CATEGORY, PUBLIC_GISCUS_CATEGORY_ID
 */
import {
  PUBLIC_GISCUS_CATEGORY,
  PUBLIC_GISCUS_CATEGORY_ID,
  PUBLIC_GISCUS_REPO,
  PUBLIC_GISCUS_REPO_ID
} from '$app/env/public';

export type GiscusConfig = {
  repo: string;
  repoId: string;
  category: string;
  categoryId: string;
  /** How a page maps onto a discussion. pathname keeps every article separate. */
  mapping: 'pathname' | 'url' | 'title' | 'og:title' | 'specific' | 'number';
  strict: '0' | '1';
  reactionsEnabled: '0' | '1';
  emitMetadata: '0' | '1';
  inputPosition: 'top' | 'bottom';
  loading: 'lazy' | 'eager';
};

const defaultRepo = 'XiaozheQAQ/xiaozhe-portal';
/** Verified through the GitHub REST API: the repos endpoint returns this as node_id. */
const defaultRepoId = 'R_kgDOVAl-3A';
/** Discussion category and its id, as generated by giscus.app for the default repo. */
const defaultCategory = 'General';
const defaultCategoryId = 'DIC_kwDOVAl-3M4DHaRM';

const repo = PUBLIC_GISCUS_REPO || defaultRepo;

export const giscusConfig: GiscusConfig = {
  repo,
  // The default id belongs to the default repo only. If the repo is overridden
  // without overriding the id, fall back to empty rather than pairing the wrong
  // repository id with the new repo.
  repoId: PUBLIC_GISCUS_REPO_ID || (repo === defaultRepo ? defaultRepoId : ''),
  category: PUBLIC_GISCUS_CATEGORY || (repo === defaultRepo ? defaultCategory : ''),
  categoryId: PUBLIC_GISCUS_CATEGORY_ID || (repo === defaultRepo ? defaultCategoryId : ''),
  mapping: 'pathname',
  strict: '1',
  reactionsEnabled: '1',
  // giscus only posts the discussion metadata (reaction + comment counts, which
  // the outline buttons mirror) when this is enabled.
  emitMetadata: '1',
  inputPosition: 'top',
  loading: 'lazy'
};

/** Deep link into the official giscus configuration page for this repository. */
export const giscusSetupUrl = `https://giscus.app/#repository=${encodeURIComponent(giscusConfig.repo)}`;

/** Giscus only works once all four identifiers are present. */
export function isGiscusConfigured(config: GiscusConfig = giscusConfig): boolean {
  return Boolean(config.repo && config.repoId && config.category && config.categoryId);
}
